### ISSUE TITLE
Can't find in US App Store when searching for Try!Swift

### ISSUE THREAD

**Issue by ZevEisenberg** [tryswift/trySwiftApp#25]
I don't think the App Store metadata is in this repo, so I can't PR a fix myself. Or maybe it's in the metadata, but App Store search is broken, in which case a radar is probably in order.

**Comment by ZevEisenberg** [comment]
For some reason, I thought the conference name was stylized as `try!Swift`, but it's not; it's `try! swift`, so maybe this isn't that important.

**Comment by BasThomas** [comment]
Apple doesn't like the `swift` name in 3rd party apps. Try searching for `try conference` - you should be able to find the app then.

**Comment by ZevEisenberg** [comment]
Fair enough. I ended up finding it when searching for "try swift", so this is probably fine 👍
